### ISSUE TITLE
java.lang.NullPointerException while doing two-factor auth

### ISSUE THREAD

**Issue by Swawm** [Erlandys/UE4LinuxLauncher#21]
When I type in my two-factor auth code and hit Confirm I got freeze and an "java.lang.NullPointerException" in terminal.

**Comment by matheusfillipe** [comment]
Same problem on ubuntu 18.04.

**Comment by Erlandys** [comment]
Try to test with new version.

**Comment by matheusfillipe** [comment]
Now i have error #1008

**Comment by Erlandys** [comment]
Two factor auth window appears, or just #1008 error?

**Comment by matheusfillipe** [comment]
just #1008

**Comment by Erlandys** [comment]
You tried with new version I updated (from develop branch), or with old one (from master branch)?

**Comment by matheusfillipe** [comment]
Develop branch.

**Comment by Erlandys** [comment]
Two factor auth enabled?

**Comment by matheusfillipe** [comment]
Yes.

**Comment by Erlandys** [comment]
Change extension to '.jar' and try again, I've added additional console logs.
[UnrealEngineLauncher.zip](https://github.com/Erlandys/UE4LinuxLauncher/files/4272316/UnrealEngineLauncher.zip)

**Comment by matheusfillipe** [comment]
400                                                                                                                                                                                                 
{"errorCode":"errors.com.epicgames.accountportal.captcha_invalid","message":"Incorrect response. Please refresh the page."}

**Comment by Erlandys** [comment]
If you can, try to go to unreal engine page through browser in private window, try to login first through website and then through launcher, if this will not help, I'll try to investigate it further, currently problem is with captcha.

**Comment by matheusfillipe** [comment]
I did log on a browser's private window and still didn't help. Same error code and message.

**Comment by Erlandys** [comment]
If you can, try this once again, if this will not help, tomorrow I'll try to check it in other PC, maybe I'll find a solution, thanks for quick feedback! :)
[UnrealEngineLauncher.zip](https://github.com/Erlandys/UE4LinuxLauncher/files/4272335/UnrealEngineLauncher.zip)

**Comment by matheusfillipe** [comment]
400
{"errorCode":"errors.com.epicgames.accountportal.captcha_invalid","message":"Incorrect response. Please refresh the page."}

Just the error message on the GUI changed to "Incorrect response. Please refresh the page."

**Comment by Swawm** [comment]
Same result as @matheusfillipe

**Comment by Erlandys** [comment]
Hello, can you try with this? (Do not forget to rename .zip to .jar)
[UnrealEngineLauncher.zip](https://github.com/Erlandys/UE4LinuxLauncher/files/4288215/UnrealEngineLauncher.zip)
@matheusfillipe, @Swawm

**Comment by Swawm** [comment]
@Erlandys  got looped window with Captcha BDA Set, when I fill all data and press Confirm login process starts again. 
Here's logs output: 
`org.sqlite.SQLiteException: [SQLITE_BUSY]  The database file is locked (database is locked)
        at org.sqlite.core.DB.newSQLException(DB.java:941)
        at org.sqlite.core.DB.newSQLException(DB.java:953)
        at org.sqlite.core.DB.throwex(DB.java:918)
        at org.sqlite.core.NativeDB._exec_utf8(Native Method)
        at org.sqlite.core.NativeDB._exec(NativeDB.java:94)
        at org.sqlite.jdbc3.JDBC3Statement.executeUpdate(JDBC3Statement.java:109)
        at launcher.objects.Session.saveCookies(Session.java:129)
        at launcher.objects.Session.save(Session.java:119)
        at launcher.objects.Session.setBDA(Session.java:65)
        at launcher.objects.Session.setBDA(Session.java:37)
        at launcher.CaptchaWorkaroundForm$PerformTwoFactor.run(CaptchaWorkaroundForm.java:161)
org.sqlite.SQLiteException: [SQLITE_BUSY]  The database file is locked (database is locked)
        at org.sqlite.core.DB.newSQLException(DB.java:941)
        at org.sqlite.core.DB.newSQLException(DB.java:953)
        at org.sqlite.core.DB.throwex(DB.java:918)
        at org.sqlite.core.NativeDB._exec_utf8(Native Method)
        at org.sqlite.core.NativeDB._exec(NativeDB.java:94)
        at org.sqlite.jdbc3.JDBC3Statement.executeUpdate(JDBC3Statement.java:109)
        at launcher.objects.Session.clearSession(Session.java:210)
        at launcher.managers.AuthenticationManager.doLogin(AuthenticationManager.java:89)
        at launcher.CaptchaWorkaroundForm$PerformTwoFactor.run(CaptchaWorkaroundForm.java:162)
400
{"errorCode":"errors.com.epicgames.accountportal.captcha_invalid","message":"Incorrect response. Please refresh the page."}
`

**Comment by Erlandys** [comment]
@Swawm 
Try this:
1. go to unreal engine page, logout, open login form
2. then open launcher
3. try to login through launcher until you get request for BDA
4. then open network tab in browser
5. perform full login (if you have two factor auth or etc) until you reach whatever page after login to make it successful
6. take that BDA and userbrowser from request in network tab
7. put them into launcher
8. try to login

P.s. check, theres new commit about 10-15minutes ago.
P.p.s. After filling the data and getting into the loop, try to close the application fully and open it again, it may help.
