### ISSUE TITLE
Login failed: Error: # 1008

### ISSUE THREAD

**Issue by SalimTerryLi** [Erlandys/UE4LinuxLauncher#22]
That was displayed on the button of window. Is current login auth out-of-date?

**Comment by Erlandys** [comment]
Try to test now.

**Comment by matheusfillipe** [comment]
I have this error now with the version released just now. 

> `~/programs/UE4LinuxLauncher/Compiled$ ./start.sh 
> java.text.ParseException: Unparseable date: "Mon, 02 Mar 2020 18:45:13 GMT"
>         at java.text.DateFormat.parse(DateFormat.java:366)
>         at launcher.objects.Request.parseHeaders(Request.java:149)
>         at launcher.objects.Request.execute(Request.java:114)
>         at launcher.managers.AuthenticationManager.captchaValidationRequest(AuthenticationManager.java:111)
>         at launcher.managers.AuthenticationManager.doLogin(AuthenticationManager.java:88)
>         at launcher.LoginForm$PerformLogin.run(LoginForm.java:143)
> java.text.ParseException: Unparseable date: "Tue, 01 Mar 2022 18:45:12 GMT"
>         at java.text.DateFormat.parse(DateFormat.java:366)
>         at launcher.objects.Request.parseHeaders(Request.java:149)
>         at launcher.objects.Request.execute(Request.java:114)
>         at launcher.managers.AuthenticationManager.captchaValidationRequest(AuthenticationManager.java:111)
>         at launcher.managers.AuthenticationManager.doLogin(AuthenticationManager.java:88)
>         at launcher.LoginForm$PerformLogin.run(LoginForm.java:143)
> java.text.ParseException: Unparseable date: "Tue, 01 Mar 2022 18:45:12 GMT"
>         at java.text.DateFormat.parse(DateFormat.java:366)
>         at launcher.objects.Request.parseHeaders(Request.java:149)
>         at launcher.objects.Request.execute(Request.java:114)
>         at launcher.managers.AuthenticationManager.captchaValidationRequest(AuthenticationManager.java:111)
>         at launcher.managers.AuthenticationManager.doLogin(AuthenticationManager.java:88)
>         at launcher.LoginForm$PerformLogin.run(LoginForm.java:143)
> java.text.ParseException: Unparseable date: "Mon, 02 Mar 2020 18:45:14 GMT"
>         at java.text.DateFormat.parse(DateFormat.java:366)
>         at launcher.objects.Request.parseHeaders(Request.java:149)
>         at launcher.objects.Request.execute(Request.java:114)
>         at launcher.managers.AuthenticationManager.retrieveCSRF(AuthenticationManager.java:190)
>         at launcher.managers.AuthenticationManager.loginRequest(AuthenticationManager.java:202)
>         at launcher.managers.AuthenticationManager.doLogin(AuthenticationManager.java:89)
>         at launcher.LoginForm$PerformLogin.run(LoginForm.java:143)
> java.text.ParseException: Unparseable date: "Mon, 02 Mar 2020 18:45:19 GMT"
>         at java.text.DateFormat.parse(DateFormat.java:366)
>         at launcher.objects.Request.parseHeaders(Request.java:149)
>         at launcher.objects.Request.execute(Request.java:114)
>         at launcher.managers.AuthenticationManager.captchaValidationRequest(AuthenticationManager.java:111)
>         at launcher.managers.AuthenticationManager.doLogin(AuthenticationManager.java:88)
>         at launcher.LoginForm$PerformLogin.run(LoginForm.java:143)
> java.text.ParseException: Unparseable date: "Tue, 01 Mar 2022 18:45:18 GMT"                                                                                                                          
>         at java.text.DateFormat.parse(DateFormat.java:366)                                                                                                                                           
>         at launcher.objects.Request.parseHeaders(Request.java:149)                                                                                                                                   
>         at launcher.objects.Request.execute(Request.java:114)                                                                                                                                        
>         at launcher.managers.AuthenticationManager.captchaValidationRequest(AuthenticationManager.java:111)                                                                                          
>         at launcher.managers.AuthenticationManager.doLogin(AuthenticationManager.java:88)                                                                                                            
>         at launcher.LoginForm$PerformLogin.run(LoginForm.java:143)                                                                                                                                   
> java.text.ParseException: Unparseable date: "Tue, 01 Mar 2022 18:45:18 GMT"
>         at java.text.DateFormat.parse(DateFormat.java:366)
>         at launcher.objects.Request.parseHeaders(Request.java:149)
>         at launcher.objects.Request.execute(Request.java:114)
>         at launcher.managers.AuthenticationManager.captchaValidationRequest(AuthenticationManager.java:111)
>         at launcher.managers.AuthenticationManager.doLogin(AuthenticationManager.java:88)
>         at launcher.LoginForm$PerformLogin.run(LoginForm.java:143)
> java.text.ParseException: Unparseable date: "Mon, 02 Mar 2020 18:45:19 GMT"
>         at java.text.DateFormat.parse(DateFormat.java:366)
>         at launcher.objects.Request.parseHeaders(Request.java:149)
>         at launcher.objects.Request.execute(Request.java:114)
>         at launcher.managers.AuthenticationManager.retrieveCSRF(AuthenticationManager.java:190)
>         at launcher.managers.AuthenticationManager.loginRequest(AuthenticationManager.java:202)
>         at launcher.managers.AuthenticationManager.doLogin(AuthenticationManager.java:89)
>         at launcher.LoginForm$PerformLogin.run(LoginForm.java:143)
> java.text.ParseException: Unparseable date: "Mon, 02 Mar 2020 18:45:41 GMT"
>         at java.text.DateFormat.parse(DateFormat.java:366)
>         at launcher.objects.Request.parseHeaders(Request.java:149)
>         at launcher.objects.Request.execute(Request.java:114)
>         at launcher.managers.AuthenticationManager.captchaValidationRequest(AuthenticationManager.java:111)
>         at launcher.managers.AuthenticationManager.doLogin(AuthenticationManager.java:88)
>         at launcher.LoginForm$PerformLogin.run(LoginForm.java:143)
> java.text.ParseException: Unparseable date: "Tue, 01 Mar 2022 18:45:40 GMT"
>         at java.text.DateFormat.parse(DateFormat.java:366)
>         at launcher.objects.Request.parseHeaders(Request.java:149)
>         at launcher.objects.Request.execute(Request.java:114)
>         at launcher.managers.AuthenticationManager.captchaValidationRequest(AuthenticationManager.java:111)
>         at launcher.managers.AuthenticationManager.doLogin(AuthenticationManager.java:88)
>         at launcher.LoginForm$PerformLogin.run(LoginForm.java:143)
> java.text.ParseException: Unparseable date: "Tue, 01 Mar 2022 18:45:40 GMT"
>         at java.text.DateFormat.parse(DateFormat.java:366)
>         at launcher.objects.Request.parseHeaders(Request.java:149)
>         at launcher.objects.Request.execute(Request.java:114)
>         at launcher.managers.AuthenticationManager.captchaValidationRequest(AuthenticationManager.java:111)
>         at launcher.managers.AuthenticationManager.doLogin(AuthenticationManager.java:88)
>         at launcher.LoginForm$PerformLogin.run(LoginForm.java:143)
> java.text.ParseException: Unparseable date: "Mon, 02 Mar 2020 18:45:41 GMT"
>         at java.text.DateFormat.parse(DateFormat.java:366)
>         at launcher.objects.Request.parseHeaders(Request.java:149)
>         at launcher.objects.Request.execute(Request.java:114)
>         at launcher.managers.AuthenticationManager.retrieveCSRF(AuthenticationManager.java:190)
>         at launcher.managers.AuthenticationManager.loginRequest(AuthenticationManager.java:202)
>         at launcher.managers.AuthenticationManager.doLogin(AuthenticationManager.java:89)
>         at launcher.LoginForm$PerformLogin.run(LoginForm.java:143)
> `

**Comment by Erlandys** [comment]
Does the system tries to go further, or it stucks at some point at authentication?
Those errors are from parsing date, which is not necessary, I'll try to investigate, to not throw this error.

**Comment by matheusfillipe** [comment]
It just gets stuck there

**Comment by alejandroua** [comment]
Having the same #1008 error on the login button with the current versions of UE4 and this script. Progress bar is showing 60%

**Comment by Erlandys** [comment]
Hello, can you try with this? (Do not forget to rename .zip to .jar)
[UnrealEngineLauncher.zip](https://github.com/Erlandys/UE4LinuxLauncher/files/4288226/UnrealEngineLauncher.zip)
@alejandroua

**Comment by alejandroua** [comment]
Hi @Erlandys , Thanks for the patch!
This time was better, I got through to the captcha (I had to input email instead of login). 
My Chrome browser refuses to ask for captcha and I had to use Opera VPN to get it asked. But then I could not track the request you mention in the instructions. Alas, I might not be knowledgeable enough in networking/browsers. Perhaps the type of captcha I've encountered is something different - I had to rotate animals :)

**Comment by matheusfillipe** [comment]
I have a different annoying issue with this. The captcha window that is popping is super small and not resizing. 
![image](https://user-images.githubusercontent.com/24435787/75905421-93842a00-5e23-11ea-9db4-6eae6d7af76a.png)

Sometimes the launcher itself has that behaviour. I am using KDE. I will try opening that on i3wm and we will see.

**Comment by Erlandys** [comment]
@alejandroua hi, you do not need to perform captcha, all you have to do is login, you may have already performed captcha before, the thing is to find the request I mentioned in description of captcha form. Add here screenshot from network requests on login. i will check it (some browsers may show not full url, but only last part)
@matheusfillipe I will try to launch KDE VM and try to open it. If you cant fill that place, you can add bda and user browser to sqlite database (data.db), global_variables table,
name - bda
value - base64 decoded bda value from request
name - user_browser
value - userbrowser from request

**Comment by Erlandys** [comment]
@alejandroua thats the request you need to be looking for:
![image](https://user-images.githubusercontent.com/6483175/75907579-399a5900-5e51-11ea-91ee-1703716d6fb9.png)

**Comment by Erlandys** [comment]
@matheusfillipe try this solution: https://stackoverflow.com/questions/52519777/java-swing-app-looks-tiny-on-high-dpi-screen-when-it-should-be-scaled-to-normal

**Comment by alejandroua** [comment]
@Erlandys Wow, I'm kind of close. I had to enable 'Persist logs' in Firefox networking since the login page was redirecting instantly to the account page. Now I enter bda and userbrowser data into the form and it just loops - asking for bda/browser again.
![image](https://user-images.githubusercontent.com/28009308/75909205-48ced600-5e54-11ea-84a4-576c8c8dabd3.png)

**Comment by Erlandys** [comment]
@alejandroua try with this:
[UnrealEngineLauncher.zip](https://github.com/Erlandys/UE4LinuxLauncher/files/4289049/UnrealEngineLauncher.zip)
Ps. rename .zip to .jar
If this will fail, can you contact me via email 'erlandys56@gmail.com'?

**Comment by Erlandys** [comment]
@matheusfillipe if you will try, try with the newest version pushed to git.

**Comment by godofdream** [comment]
I'm trying with the Version in Develop Branch, and when filling BDA and useragent I'm getting:

```
Exception in thread "Thread-1" org.json.JSONException: A JSONArray text must start with '[' at 1 [character 2 line 1]
	at org.json.JSONTokener.syntaxError(JSONTokener.java:505)
	at org.json.JSONArray.<init>(JSONArray.java:108)
	at org.json.JSONArray.<init>(JSONArray.java:161)
	at launcher.objects.Session.setBDA(Session.java:51)
	at launcher.objects.Session.setBDA(Session.java:37)
	at launcher.CaptchaWorkaroundForm$PerformTwoFactor.run(CaptchaWorkaroundForm.java:161)
```

EDIT:style

**Comment by ben-mkiv** [comment]
@godofdream what java runtime do you use? oracle or openjdk?

**Comment by godofdream** [comment]
@ben-mkiv 

```
java --version
openjdk 13 2019-09-17
OpenJDK Runtime Environment (build 13+33-Ubuntu-1)
OpenJDK 64-Bit Server VM (build 13+33-Ubuntu-1, mixed mode)
```

**Comment by ben-mkiv** [comment]
ok, sadly i can now confirm the issue as i cant login anymore, on the website it requires the captcha everytime i try to login (could you please check if that also applies to you)

(btw. its not related to the Java runtime as it happens to me with oracle, too)

**Comment by Roman-Malinowski** [comment]
Hi, 

When I enter my bda and userbrowser I get this error 
```
Exception in thread "Thread-1" org.json.JSONException: A JSONArray text must start with '[' at 1 [character 2 line 1]
	at org.json.JSONTokener.syntaxError(JSONTokener.java:505)
	at org.json.JSONArray.<init>(JSONArray.java:108)
	at org.json.JSONArray.<init>(JSONArray.java:161)
	at launcher.objects.Session.setBDA(Session.java:51)
	at launcher.objects.Session.setBDA(Session.java:37)
	at launcher.CaptchaWorkaroundForm$PerformTwoFactor.run(CaptchaWorkaroundForm.java:161)
```
I don't know if this is due to the fact that my bda ends with a ```VhIn0=``` or not.
Do you have an idea on how I can fix this?

Thank you for the project!

**Comment by ben-mkiv** [comment]
@godofdream @Roman-Malinowski 

this build might fix the login issue
https://github.com/ben-mkiv/UE4LinuxLauncher/tree/develop/Compiled

**Comment by kihaki** [comment]
I am encountering the same issue on the current develop branch:

```
Exception in thread "Thread-6" org.json.JSONException: A JSONArray text must start with '[' at 1 [character 2 line 1]
	at org.json.JSONTokener.syntaxError(JSONTokener.java:505)
	at org.json.JSONArray.<init>(JSONArray.java:108)
	at org.json.JSONArray.<init>(JSONArray.java:161)
	at launcher.objects.Session.setBDA(Session.java:51)
	at launcher.objects.Session.setBDA(Session.java:37)
	at launcher.CaptchaWorkaroundForm$PerformTwoFactor.run(CaptchaWorkaroundForm.java:161)
```

I guess the server response cannot be parsed. Can we enable logs somehow to log the response? It would probably give you a more clear picture of what is happening.
