### ISSUE TITLE
How to start this program?

### ISSUE THREAD

**Issue by Pattern-Projects** [Erlandys/UE4LinuxLauncher#5]
I'm new to Linux, using fedorea. 
Can you describe the start procedure in the README.md.

I've tried:
./Compiled/start.sh
The result is:
Error: Could not find or load main class launcher.Main

**Comment by LinuxDonald** [comment]
First do an cd Compiled and than ./start.sh

**Comment by Pattern-Projects** [comment]
The error that comes up is:
`Exception in thread "main" java.awt.HeadlessException
	at java.awt.GraphicsEnvironment.checkHeadless(GraphicsEnvironment.java:204)
	at java.awt.Window.<init>(Window.java:536)
	at java.awt.Frame.<init>(Frame.java:420)
	at javax.swing.JFrame.<init>(JFrame.java:233)
	at launcher.LoginForm.<init>(LoginForm.java:20)
	at launcher.Main.checkIfLoggedIn(Main.java:61)
	at launcher.Main.<init>(Main.java:55)
	at launcher.Main.main(Main.java:19)
`

**Comment by infinityplusb** [comment]
This is a recent issue, since the last update which fixed oauth.

**Comment by LinuxDonald** [comment]
I dont have any problems Ubuntu 18.04
Java:

java version "1.8.0_181"
Java(TM) SE Runtime Environment (build 1.8.0_181-b13)
Java HotSpot(TM) 64-Bit Server VM (build 25.181-b13, mixed mode)

**Comment by ChrisY03** [comment]
I literally have no idea what I'm doing. I'm using Ubuntu. Can someone please write the exact command I need in terminal to start this?

**Comment by infinityplusb** [comment]
Download
```
cd Compiled
./start.sh
```
Profit
