### ISSUE TITLE
Another Login Error :(

### ISSUE THREAD

**Issue by infinityplusb** [Erlandys/UE4LinuxLauncher#9]
On trying to launch it gets stuck at 16% 

```
$ ./start.sh 
Exception in thread "Thread-0" java.lang.ArrayIndexOutOfBoundsException: 1
	at launcher.EpicAPI.getCookies(EpicAPI.java:236)
	at launcher.EpicAPI.doLogin(EpicAPI.java:300)
	at launcher.LoginForm$PerformLogin.run(LoginForm.java:125)
```
Fails with both Open Java and Oracle Java 
``` 
$ java -version
java version "1.8.0_191"
Java(TM) SE Runtime Environment (build 1.8.0_191-b12)
Java HotSpot(TM) 64-Bit Server VM (build 25.191-b12, mixed mode)
```

**Comment by infinityplusb** [comment]
I removed and reinstalled the code base. Now getting the same issue as #8
